timesheet/lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetWeb.Plugs.FetchCurrentManager
    plug TimesheetWeb.Plugs.FetchCurrentWorker
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/managers", ManagerController
    resources "/workers", WorkerController
    resources "/jobs", JobController
    resources "/sessionmanager", SessionmanagerController, only: [:new, :create, :delete], singleton: true
    resources "/sessionworker", SessionworkerController, only: [:new, :create, :delete], singleton: true
    resources "/jobs", JobController, only: [:new, :create]
    resources "/tasks", TaskController, only: [:new, :create, :edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

timesheet/lib/timesheet_web/templates/page/index.html.eex
        <style> 
			#wrapper {
	  			display: flex;
			}
			
			#left {
  				flex: 0 0 65%;
			}
			
			#right {
  				flex: 1;
			}
		</style>
        
        <%= if @current_user do %>
        	User: <%= @current_user.name %>
            (<%= link("Logout", to: Routes.sessionmanager_path(@conn, :delete),
              method: :delete) %>)
        <% else %>
    		<div id="wrapper">
  			<div id="left"><div class="col-4 text-light">
        	<h3><center> Manager Login </center></h3>
          	<center><%= link("Login", to: Routes.sessionmanager_path(@conn, :new)) %></center>
        	</div></div>
  			<div id="right"><div class="col-4 text-light">
        	<h3><center> Worker Login </center></h3>
          	<center><%= link("Login", to: Routes.sessionworker_path(@conn, :new)) %></center>
        	</div></div>
			</div>
        <% end %>